apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aap
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: demo-gitops-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: aap-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/ogleo/acm-argo-multi.git
        targetRevision: main
        path: operators/ansible-automation-platform/base
      destination:
        namespace: aap
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: false