---
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: averbit
  namespace: aap
spec:
  replicas: 1