---
kind: AutomationHub
apiVersion: automationhub.ansible.com/v1beta1
metadata:
  namespace: aap
  name: averbit-hub
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true